# Generated by Django 5.0.3 on 2024-03-25 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseDate', models.CharField(max_length=8)),
                ('baseTime', models.CharField(max_length=4)),
                ('fcstDate', models.CharField(max_length=8)),
                ('fcstTime', models.CharField(max_length=4)),
                ('fcstValue', models.CharField(max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.category')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nx', models.IntegerField()),
                ('ny', models.IntegerField()),
            ],
            options={
                'unique_together': {('nx', 'ny')},
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseDate', models.CharField(max_length=8)),
                ('baseTime', models.CharField(max_length=4)),
                ('obsrValue', models.CharField(max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.location')),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
        migrations.AddField(
            model_name='forecast',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.location'),
        ),
    ]
