# Generated by Django 5.0.3 on 2024-03-26 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_category_forecast_location_observation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='observation',
            unique_together={('location', 'category')},
        ),
    ]
