# Generated by Django 5.0.3 on 2024-03-26 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_observation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltraShortForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseDate', models.CharField(max_length=8)),
                ('baseTime', models.CharField(max_length=4)),
                ('obsrValue', models.CharField(max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.location')),
            ],
            options={
                'unique_together': {('location', 'category', 'baseDate', 'baseTime')},
            },
        ),
    ]
