# Generated by Django 5.0.3 on 2024-03-26 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_ultrashortforecast'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ultrashortforecast',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ultrashortforecast',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.location', unique=True),
        ),
    ]
