# Generated by Django 5.0.3 on 2024-03-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_ultrashortforecast_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UltraShortForecast',
        ),
    ]
