# Generated by Django 5.0.3 on 2024-03-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_shortforecast'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shortforecast',
            unique_together={('location', 'category', 'baseDate', 'baseTime', 'fcstDate', 'fcstTime')},
        ),
    ]
